# Arquivo para armazenar constantes e strings frequentemente usadas.

# Nomes de colunas do Excel
EXCEL_COL_PROCESSO = "PROCESSO"
EXCEL_COL_DATA_MOVIMENTACAO = "DATA_ULTIMA_MOVIMENTACAO"
EXCEL_COL_DESCRICAO_MOVIMENTACAO = "DESCRICAO_ULTIMA_MOVIMENTACAO"
EXCEL_COL_REQUERIDO_EXECUTADO = "REQUERIDO/EXECUTADO"
EXCEL_COL_PROCESSO_LOWER = "processo" # Para compatibilidade

# Mensagens/Status Comuns
STATUS_NAO_DISPONIVEL = "N/A"
STATUS_NUMERO_INVALIDO = "NÚMERO DE PROCESSO INVÁLIDO"
STATUS_SEGREDO_JUSTICA = "SEGREDO DE JUSTIÇA"
STATUS_MOVIMENTACAO_NAO_ENCONTRADA = "MOVIMENTAÇÃO NÃO ENCONTRADA"
STATUS_DADOS_NAO_ENCONTRADOS = "DADOS NÃO ENCONTRADOS"
STATUS_DATA_NAO_ENCONTRADA = "DATA NÃO ENCONTRADA"
STATUS_DESCRICAO_NAO_ENCONTRADA = "DESCRIÇÃO NÃO ENCONTRADA"
STATUS_ERRO_GENERICO = "ERRO GERAL"
STATUS_CONSULTA_FALHOU = "CONSULTA FALHOU"

# Mensagens de Erro PROJUDI
PROJUDI_ERRO_CREDENCIAIS_NAO_FORNECIDAS = "Credenciais do PROJUDI não fornecidas para a consulta."
PROJUDI_ERRO_CREDENCIAIS_INVALIDAS = "Credenciais inválidas ou problema no login."
PROJUDI_ERRO_USERMAINFRAME = "Erro PROJUDI (userMainFrame)"
PROJUDI_ERRO_PREENCHIMENTO = "Erro PROJUDI (Preenchimento)"
PROJUDI_ERRO_TIMEOUT_MOV = "Erro PROJUDI (Timeout Mov)"
PROJUDI_ERRO_ELEMENTO_MOV_N_E = "Erro PROJUDI (Elemento Mov N/E)"
PROJUDI_ERRO_MOVIMENTACAO = "Erro PROJUDI (Movimentação)"
PROJUDI_ERRO_TIMEOUT_GERAL = "Erro PROJUDI (Timeout Geral)"
PROJUDI_ERRO_ELEMENTO_GERAL_N_E = "Erro PROJUDI (Elemento Geral N/E)"
PROJUDI_ERRO_WEBDRIVER = "Erro PROJUDI (WebDriver)"
PROJUDI_ERRO_GERAL = "Erro PROJUDI (Geral)"
PROJUDI_PROCESS_NAO_ENCONTRADO = "NENHUM REGISTRO ENCONTRADO OU NÚMERO DE PROCESSO INVÁLIDO"
PROJUDI_PROCESS_NAO_LISTADO_POS_BUSCA = "PROJUDI: PROCESSO NÃO LISTADO APÓS BUSCA"
PROJUDI_ERRO_TABELA_MOVIMENTACAO_N_E = "TABELA DE MOVIMENTAÇÃO NÃO ENCONTRADA"
PROJUDI_ERRO_NENHUMA_MOVIMENTACAO_ENCONTRADA = "NENHUMA MOVIMENTAÇÃO ENCONTRADA"
PROJUDI_ERRO_TIMEOUT_TABELA = "Erro PROJUDI (Timeout Tabela)"
PROJUDI_ERRO_ELEMENTO_N_E = "Erro PROJUDI (Elemento N/E)"
PROJUDI_ERRO_EXTRACAO = "Erro PROJUDI (Extração)"
PROJUDI_ERRO_ELEMENTO_OBSOLETO = "Erro PROJUDI (Elemento Obsoleto)"

# Tempos de espera (time.sleep) - Podem ser ajustados no futuro, mas são mantidos como constantes
SLEEP_LOGIN_PROJUDI = 5
SLEEP_MENU_PROJUDI = 3
SLEEP_FRAME_CHANGE_PROJUDI = 4
SLEEP_FIELD_FILL_PROJUDI = 2
SLEEP_SEARCH_PROJUDI = 4
SLEEP_AFTER_PROJUDI_CONSULTA = 3
SLEEP_TABLE_RETRY = 3
SLEEP_PAGE_LOAD = 5


# Configurações do Keyring
KEYRING_SERVICE_RPA_NAME = "RPA_TJAM_PROJUDI"